README.md

fix typo: aspiring

---

app/layout.tsx

Remove banner for application deadline

remove banner

---

app/career/page.tsx

fix: remove seminar copy

---

package-lock.json
public/opensource-projects/index.json

- Added open source project structure with the required parameters

Feat: Projects file structure

---

app/projects/page.tsx
graphql/queries/get-issues.ts
scripts/graphql/queries/get-issues.js
scripts/utils/index.js
scripts/utils/sanitize.js
scripts/utils/slugify.js
tsconfig.scripts.json
utils/index.ts

The import paths for the `IssueCardElement` type and the `sanitize` function in the `utils` directory have been updated to reflect the new file structure. Additionally, the `tsconfig.scripts.json` file has been modified to include the `utils` and `types` directories in the TypeScript compilation process.

feat: Update import paths for utils and types

---

components/repository-issues.tsx
graphql/queries/get-issues.ts
helpers/fetch-issues.ts
public/open-source-projects/issues/bdk/index.json
public/open-source-projects/issues/bdkffi/index.json
public/open-source-projects/issues/bitcoin/index.json
public/open-source-projects/issues/btcpayserver/index.json
public/open-source-projects/issues/eclair/index.json
public/open-source-projects/issues/fedimint/index.json
public/open-source-projects/issues/lightning/index.json
public/open-source-projects/issues/lnd/index.json
public/open-source-projects/issues/polar/index.json
public/open-source-projects/issues/rustlightning/index.json
public/open-source-projects/issues/simln/index.json
public/open-source-projects/issues/stratum/index.json
public/open-source-projects/issues/ui/index.json
public/open-source-projects/issues/warnet/index.json
scripts/graphql/queries/get-issues.js
scripts/helpers/fetch-issues.js
types/index.ts

This pull request modifies the graphQl query to add repository image to be displayed in the issue card component

feat: add images to issue cards

---

app/layout.tsx
components/repository-issues.tsx
components/sidebar-filter.tsx

- fix filter bugginess
- fix issue card displacement due to min height
- Capitalize the issue and repo name

fix: grid positioning and filter bugginess

---

components/page-level.tsx
components/repository-issues.tsx

Improve good first issues copy text and make positioning to be fixed

enhancement: Good first issues page copy text

---

app/career/page.tsx
app/layout.tsx
app/page.tsx
components/badge.tsx
components/drawer.tsx
components/footer.tsx
components/nav-bar.tsx
components/navbar-dropdown.tsx
components/page-level.tsx
components/pointer.tsx
components/repository-issues.tsx
components/section-card.tsx
components/tools-card.tsx

Adds umami analytics to app using #28 as a guideline

add umami analytics to app

---

components/sidebar-filter.tsx

Improve sorting functionality with custom sort to accommodate for alphabetical sorting

chore: create custom sort functionality

---

components/badge.tsx
components/page-level.tsx
components/repository-issues.tsx
public/open-source-projects/index.json

- Add underline when issue tilte is hovered
- remove good first issue icon
- remove capitalization of issue owner/repo

chore: ui updates

---

app/career/page.tsx
app/layout.tsx
components/navbar-dropdown.tsx
components/repository-issues.tsx
components/search-input.tsx
components/sidebar-filter.tsx

fixes:
1. ValidateDomStringError in console for careers page
2. Image sizing error in console
3. Input placeholder text sizing for mobile
4. modify copy of good first issues page

fix: good first issues post launch issues

---

app/page.tsx
components/footer.tsx
components/header.tsx
components/hero/CTA.tsx
components/hero/SecondaryFeatures.tsx
components/hero/WhoAreWe.tsx
components/hero/newsletter.tsx
components/repository-issues.tsx
content/landing.tsx
hooks/useOnclickOut.ts

- This PR attends to different text fixes and corrections from this [deployment](https://bitcoin-dev-project-git-staging-btc-knowledge-base.vercel.app/)

fixes: copytext and style changes

---

components/hero/Hero.tsx

rm button from hero pointing to good first issues

---

components/hero/Hero.tsx
content/landing.tsx

* make the products logo in the landig page
* change the variable name

Make products logo in the landig page clickable (#118)

---

app/globals.css
components/banner/BossBanner.tsx
components/bitcoin-topics/hero/Hero.tsx
components/bitcoin-topics/layouts/BaseLayout.tsx
components/header.tsx
package-lock.json
package.json
tailwind.config.ts

* chore(banner): add Boss banner
* fix(version): bdp-ui version update
* chore(banner): added banner to good first issues
* fix(design): overflow in decoding and z-index issue with menu
* refactor(BaseLayout): remove hardcoded top styling on mobile navigation
---------

Add Boss banner (#130)

---

components/header.tsx

Queued Removal of boss banner

---

README.md

This PR updates the README to include the image path `public/images/landscape_2_1.jpg`, which is currently unused elsewhere in the project.

fix: update image path in README.md

---

.github/workflows/trigger-deploy-from-submodule-update.yml
.gitmodules
components/bitcoin-topics/Navigation.tsx
components/bitcoin-topics/markdown-ui/MDXComponents.tsx
content/transaction-animation-player.tsx
src/components/TransactionCreation.tsx

This PR adds two new components needed for some markdowns in the Transaction module:
1- TransactionCreation: Displays different transaction fields and explains each one
2- TransactionAnimationPlayer:  Used for displaying the transaction lifecycle in an animated way

Transaction module

---

content/opcode-explorer.tsx

This PR resolves the stack simulator's behavior issues as outlined in #117.
Fix #117.

fix(stack-simulator): convert boolean to BigInt

---

app/.well-known/nostr.json/nostr.json

Merging staging to master will deploy the NIP-05 identifiers

Merge Staging to Master

---

components/decoding-bitcoin/markdown-ui/MDXComponents.tsx
components/decoding-bitcoin/markdown-ui/hash-functions.tsx

New Hash functions section added

Add hash functions tool section

---

components/decoding-bitcoin/markdown-ui/MDXComponents.tsx
components/decoding-bitcoin/markdown-ui/address-generator.tsx
components/decoding-bitcoin/markdown-ui/byte-tools.tsx
components/decoding-bitcoin/markdown-ui/hash-functions.tsx

This PR adds new tools that users can use for the transaction module on decoding-bitcoin, and improves the UI of the hash function tool:
Tools: 
- Bitcoin Address Generator (P2PKH, P2SH, P2WPKH, P2WSH, P2TR)
- Byte Tools (Reverse Bytes, Little Endian, Base Converter, Compact Size)
- Improved the UI for hash functions

Add new tools for decoding

---

content/tools.ts

Add SimLn to tools
